# ../../bin/create-or-update-cw-stack.bash sqs-interface-endpoint.yaml SQS-ENDPOINT NO
# aws sqs send-message --queue-url https://sqs.us-east-1.amazonaws.com/677276112527/test-q --message-body "Hello, SQS"
AWSTemplateFormatVersion: '2010-09-09'
Description: Centralized SQS Interface Endpoint with Transit Gateway and Route 53 Private Hosted Zone

Parameters:
  SharedServicesVPCCidr:
    Type: String
    Default: 10.0.0.0/16
    Description: CIDR block for the Shared Services VPC

  ProductionVPC1Cidr:
    Type: String
    Default: 10.1.0.0/16
    Description: CIDR block for Production VPC 1

  ProductionVPC2Cidr:
    Type: String
    Default: 10.2.0.0/16
    Description: CIDR block for Production VPC 2

  Region:
    Type: String
    Default: us-east-1
    Description: AWS region where resources will be deployed

Resources:
  # Shared Services VPC
  SharedServicesVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref SharedServicesVPCCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: SharedServicesVPC

  # Subnets in Shared Services VPC
  SharedServicesSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref SharedServicesVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs ]

  SharedServicesSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref SharedServicesVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [1, !GetAZs ]

  # Production VPC 1
  ProductionVPC1:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref ProductionVPC1Cidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: ProductionVPC1

  ProductionVPC1Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ProductionVPC1
      CidrBlock: 10.1.1.0/24
      AvailabilityZone: !Select [0, !GetAZs ]

  ProductionVPC1SubnetRt:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref ProductionVPC1
      Tags:
        - Key: Name
          Value: ProductionVPC1SubnetRt

  Route1ToSharedServicesVPC:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref ProductionVPC1SubnetRt
      DestinationCidrBlock: !Ref SharedServicesVPCCidr
      TransitGatewayId: !Ref TransitGateway

  PrivateRouteTableAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref ProductionVPC1Subnet
      RouteTableId: !Ref ProductionVPC1SubnetRt

  # Production VPC 2
  ProductionVPC2:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref ProductionVPC2Cidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: ProductionVPC2

  ProductionVPC2Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ProductionVPC2
      CidrBlock: 10.2.1.0/24
      AvailabilityZone: !Select [0, !GetAZs ]

  ProductionVPC2SubnetRt:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref ProductionVPC2
      Tags:
        - Key: Name
          Value: ProductionVPC2SubnetRt

  Route2ToSharedServicesVPC:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref ProductionVPC2SubnetRt
      DestinationCidrBlock: !Ref SharedServicesVPCCidr
      TransitGatewayId: !Ref TransitGateway

  PrivateRouteTableAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref ProductionVPC2Subnet
      RouteTableId: !Ref ProductionVPC2SubnetRt

  # SQS Interface Endpoint in Shared Services VPC
  SQSEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref SharedServicesVPC
      ServiceName: !Sub com.amazonaws.${Region}.sqs
      VpcEndpointType: Interface
      SubnetIds:
        - !Ref SharedServicesSubnet1
        - !Ref SharedServicesSubnet2
      SecurityGroupIds:
        - !Ref SQSEndpointSecurityGroup
      PrivateDnsEnabled: true
      Tags:
        - Key: Name
          Value: SQSInterfaceEndpoint

  # Security Group for SQS Endpoint
  SQSEndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for SQS Interface Endpoint
      VpcId: !Ref SharedServicesVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !Ref SharedServicesVPCCidr
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !Ref ProductionVPC1Cidr
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !Ref ProductionVPC2Cidr

  # Transit Gateway
  TransitGateway:
    Type: AWS::EC2::TransitGateway
    Properties:
      Description: Transit Gateway for Shared Services and Production VPCs
      AutoAcceptSharedAttachments: enable

  # Attach Shared Services VPC to Transit Gateway
  SharedServicesTGWAttachment:
    Type: AWS::EC2::TransitGatewayVpcAttachment
    Properties:
      TransitGatewayId: !Ref TransitGateway
      VpcId: !Ref SharedServicesVPC
      SubnetIds:
        - !Ref SharedServicesSubnet1
        - !Ref SharedServicesSubnet2
      Tags:
        - Key: Name
          Value: SharedVPC_TGW_Attachment

  # Attach Production VPC 1 to Transit Gateway
  ProductionVPC1TGWAttachment:
    Type: AWS::EC2::TransitGatewayVpcAttachment
    Properties:
      TransitGatewayId: !Ref TransitGateway
      VpcId: !Ref ProductionVPC1
      SubnetIds:
        - !Ref ProductionVPC1Subnet
      Tags:
        - Key: Name
          Value: VPC1_TGW_Attachment

  # Attach Production VPC 2 to Transit Gateway
  ProductionVPC2TGWAttachment:
    Type: AWS::EC2::TransitGatewayVpcAttachment
    Properties:
      TransitGatewayId: !Ref TransitGateway
      VpcId: !Ref ProductionVPC2
      SubnetIds:
        - !Ref ProductionVPC2Subnet
      Tags:
        - Key: Name
          Value: VPC2_TGW_Attachment

  # Route 53 Private Hosted Zone
  PrivateHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Sub sqs.${Region}.amazonaws.com
      VPCs:
        - VPCId: !Ref ProductionVPC1
          VPCRegion: !Ref Region
        - VPCId: !Ref ProductionVPC2
          VPCRegion: !Ref Region

  OutboundResolverEndpoint:
    Type: AWS::Route53Resolver::ResolverEndpoint
    Properties:
      Direction: "OUTBOUND"
      Name: "SQS-IE-Outbound-EP"
      SecurityGroupIds:
        - !Ref SQSEndpointSecurityGroup
      IpAddresses:
        - SubnetId: !Ref SharedServicesSubnet1
        - SubnetId: !Ref SharedServicesSubnet2

  SQSIEResolverRule:
    Type: AWS::Route53Resolver::ResolverRule
    Properties:
      DomainName: "sqs.us-east-1.amazonaws.com"
      RuleType: "FORWARD"
      Name: "SQS-IE-Rule"
      ResolverEndpointId: !Ref OutboundResolverEndpoint
      TargetIps:
        - Ip: !Join [".", [!Select ["0", !Split [".", !Select ["0", !Split ["/", !Ref "SharedServicesVPCCidr"]]]], !Select ["1", !Split [".", !Select ["0", !Split ["/", !Ref "SharedServicesVPCCidr"]]]], "0", "2"]]

  SQSIEResolverRuleAssociation1:
    Type: AWS::Route53Resolver::ResolverRuleAssociation
    Properties:
      Name: "SQS-IE-Rule-Association-ProdVPC1"
      ResolverRuleId: !Ref SQSIEResolverRule
      VPCId: !Ref ProductionVPC1

  SQSIEResolverRuleAssociation2:
    Type: AWS::Route53Resolver::ResolverRuleAssociation
    Properties:
      Name: "SQS-IE-Rule-Association-ProdVPC2"
      ResolverRuleId: !Ref SQSIEResolverRule
      VPCId: !Ref ProductionVPC2

Outputs:
  SharedServicesVPCId:
    Description: ID of the Shared Services VPC
    Value: !Ref SharedServicesVPC

  ProductionVPC1Id:
    Description: ID of the Production VPC1
    Value: !Ref ProductionVPC1
    Export:
      Name: ProductionVPC1-ID

  ProductionVPC2Id:
    Description: ID of the Production VPC2
    Value: !Ref ProductionVPC2
    Export:
      Name: ProductionVPC2-ID

  ProductionVPC1Subnet:
    Description: Prod VPC1 Subnet
    Value: !Ref ProductionVPC1Subnet
    Export:
      Name: ProductionVPC1Subnet

  ProductionVPC2Subnet:
    Description: Prod VPC2 Subnet
    Value: !Ref ProductionVPC2Subnet
    Export:
      Name: ProductionVPC2Subnet

  SQSEndpointId:
    Description: ID of the SQS Interface Endpoint
    Value: !Ref SQSEndpoint

  TransitGatewayId:
    Description: ID of the Transit Gateway
    Value: !Ref TransitGateway

  #PrivateHostedZoneId:
    #Description: ID of the Route 53 Private Hosted Zone
    #Value: !Ref PrivateHostedZone