# Creates interface endpoint service that uses already created NLB in another template and an endpoint that uses the service
# ../../bin/create-or-update-cw-stack.bash endpoint-service.yaml KCSTEMP-ENDPOINTS NO
AWSTemplateFormatVersion: '2010-09-09'
Description: Template to interface endpoint service that uses already created NLB in another template and an endpoint that uses the service 
Resources:
  NLBEndPointService:
    Type: AWS::EC2::VPCEndpointService
    Properties:
      AcceptanceRequired: false
      NetworkLoadBalancerArns:
        - !ImportValue  NLBARN
      Tags:
        - Key: Name
          Value: NLBEndPointService

  EndpointSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for the endpoint
      VpcId: !ImportValue  CustomerVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 10.0.1.0/16
      Tags:
        - Key: Name
          Value: EndpointSG

  NLBEndPoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Interface
      SecurityGroupIds:
        - !Ref  EndpointSG
      ServiceName: !Sub 
        - "com.amazonaws.vpce.${AWS::Region}.${ServiceName}"
        - ServiceName: !Ref NLBEndPointService
      SubnetIds:
        - !ImportValue CustomerPrivateSubnetIdVPC
      VpcId: !ImportValue  CustomerVPC
      Tags:
        - Key: Name
          Value: NLBEndPoint
Outputs:
  NLBEndPointService:
    Description: NLBEndPointService
    Value: !Ref NLBEndPointService
    Export:
      Name: NLBEndPointService
  NLBEndPoint:
    Description: NLBEndPoint
    Value: !Ref NLBEndPoint
    Export:
      Name: NLBEndPoint
  NLBEndPointSG:
    Description: NLBEndPointSG
    Value: !Ref EndpointSG
    Export:
      Name: NLBEndPointSG