CREATE USER staging_adm;
\password staging_adm
ALTER ROLE staging_adm WITH LOGIN;
GRANT CONNECT ON DATABASE nominis_staging TO staging_adm;
GRANT USAGE, CREATE ON SCHEMA public TO staging_adm;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO staging_adm;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO staging_adm;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO staging_adm;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO staging_adm;
