# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terragrunt-state-bucket-kcs"
    dynamodb_table = "terraform-locks"
    encrypt        = true
    key            = "environments/dev/s3/terraform.tfstate"
    region         = "us-east-1"
  }
}
